---

- name: install zookeeper packages
  yum: name={{ item }} state=installed
  with_items:
    - libzookeeper
    - zookeeper


- name: Create directory for snapshot files and myid file
  file:
    path: '{{ zookeeper_data_dir }}'
    state: directory
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
  tags:
    - zookeeper_dirs

- name: Create directory for transaction log files
  file:
    path: '{{ zookeeper_data_log_dir }}'
    state: directory
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
  tags:
    - zookeeper_dirs

- name: Create zookeeper log directory
  file:
    path: '{{ zookeeper_log_dir }}'
    state: directory
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
  tags:
    - zookeeper_dirs

- name: Template configuration file to zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/zoo.cfg
  notify:
    - restart zookeeper
  tags:
    - zookeeper_config

- name: Template myid to {{ zookeeper_data_dir}}/myid
  template:
    src: myid.j2
    dest: '{{ zookeeper_data_dir }}/myid'
  notify:
    - restart zookeeper
  tags:
    - zookeeper_config

## Uncomment the log4j.properties line for setting the maximum number of logs to rollover and keep
#- name: Set maximum log rollover history
#  replace:
#    dest: /etc/zookeeper/log4j.properties
#    regexp: '^#log4j.appender.ROLLINGFILE.MaxBackupIndex'
#    replace: 'log4j.appender.ROLLINGFILE.MaxBackupIndex'
#  notify:
#    - restart zookeeper
#  tags:
#    - zookeeper_config
#
- name: Start the ZooKeeper service
  service:
    name: zookeeper
    state: started
    enabled: yes
  tags:
    - zookeeper_service


# Set Ansible fact that ZooKeeper has completed installation. This is so that this role can be used in
# other dependent roles. Those roles can check for this fact to determine whether or not this role
# should be run. Failing to do so will mean that this role is executed even if it has already been run.
- name: Set fact zookeeper_installed
  set_fact:
    zookeeper_installed: true
  tags:
    - zookeeper_install_fact
